export default {
	locale: {
		accept: 'Aceptar',
		reject: 'Rechazar',
		lt: 'Menor a',
		lte: 'Menor o igual a',
		choose: 'Elegir',
		upload: 'Subir',
		cancel: 'Cancelar',
		//...

		startsWith: 'Empieza con',
		contains: 'Contains',
		notContains: 'Not contains',
		endsWith: 'Ends with',
		equals: 'Equals',
		notEquals: 'Not equals',
		noFilter: 'No Filter',
		gt: 'Greater than',
		gte: 'Greater than or equal to',
		dateIs: 'Date is',
		dateIsNot: 'Date is not',
		dateBefore: 'Date is before',
		dateAfter: 'Date is after',
		clear: 'Clear',
		apply: 'Apply',
		matchAll: 'Match All',
		matchAny: 'Match Any',
		addRule: 'Add Rule',
		removeRule: 'Remove Rule',
		completed: 'Completed',
		pending: 'Pending',
		dayNames: [
			'Domingo',
			'Lunes',
			'Martes',
			'Miercoles',
			'Jueves',
			'Viernes',
			'Sabado'
		],
		dayNamesShort: [
			'Dom',
			'Lun',
			'Mar',
			'Mier',
			'Jue',
			'Vie',
			'Sab'
		],
		dayNamesMin: [
			'Do',
			'Lu',
			'Ma',
			'Mi',
			'Ju',
			'Vi',
			'Sa'
		],
		monthNames: [
			'Enero',
			'Febrero',
			'Marzo',
			'Abril',
			'Mayo',
			'Junio',
			'Julio',
			'Agosto',
			'Septiembre',
			'Octubre',
			'Noviembre',
			'Diciembre'
		],
		monthNamesShort: [
			'Ene',
			'Feb',
			'Mar',
			'Abr',
			'May',
			'Jun',
			'Jul',
			'Ago',
			'Sep',
			'Oct',
			'Nov',
			'Dic'
		],
		chooseYear: 'Elige Año',
		chooseMonth: 'Elije Mes',
		chooseDate: 'Elije Fecha',
		prevDecade: 'Década previa',
		nextDecade: 'Década próxima',
		prevYear: 'Año Previo',
		nextYear: 'Año Siguiente',
		prevMonth: 'Mes Previo',
		nextMonth: 'Mes Próximo',
		prevHour: 'Hora Previa',
		nextHour: 'Próxima hora',
		prevMinute: 'Minuto Previo',
		nextMinute: 'Minuto Próximo',
		prevSecond: 'Segundo previo',
		nextSecond: 'Segundo Próximo',
		am: 'am',
		pm: 'pm',
		today: 'Hoy',
		weekHeader: 'Wk',
		firstDayOfWeek: 0,
		dateFormat: 'mm/dd/yy',
		weak: 'Weak',
		medium: 'Medium',
		strong: 'Strong',
		passwordPrompt: 'ingrese una contraseña',
		emptyFilterMessage: 'No hay resultados encontrados', // @deprecated Use 'emptySearchMessage' option instead.
		searchMessage: '{0} resultados disponibles',
		selectionMessage: '{0} items seleccionados',
		emptySelectionMessage: 'No hay items seleccionados',
		emptySearchMessage: 'No hay resultados encontrados',
		emptyMessage: 'No hay opciones disponibles',
		aria: {
			trueLabel: 'True',
			falseLabel: 'False',
			nullLabel: 'Not Selected',
			star: '1 star',
			stars: '{star} stars',
			selectAll: 'All items selected',
			unselectAll: 'All items unselected',
			close: 'Close',
			previous: 'Previous',
			next: 'Next',
			navigation: 'Navigation',
			slideNumber: 'Slide {slideNumber} of {totalSlides}', // Formato para aria.slideNumber
			pageLabel: 'Page {page}' // Formato para aria.pageLabel
		}
	}
};